# Generated by Django 4.0.2 on 2022-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
